"""Generate src/data/features.generated.js from the source spreadsheet.

Run:  python3 scripts/extract-features.py
The 44 feature strings are never retyped by hand; this is their only
transcription. The spreadsheet merges cells down, so a blank Proposed
Application or Module cell means "same as the row above" — hence the carry
variables below.
"""
import json
import re

import openpyxl

SRC = "source-data/2nd_year_EA_Applications_1.xlsx"
OUT = "src/data/features.generated.js"
TARGET = "Agriculture and Livestock Management Application"

# Spreadsheet module name -> the key used in features.generated.js.
KEYS = {
    "Agricultural Land Profiling": "landProfiling",
    "Agriculture Inputs Management": "inputs",
    "Crop Monitoring and Forecasting": "cropMonitoring",
    "Farmer Advisory": "advisory",
    "Agricultural Value Chain Mapping": "valueChain",
    "Livestock Information Mapping": "livestock",
}

ws = openpyxl.load_workbook(SRC, data_only=True).active
app = module = None
features = {}

for row in ws.iter_rows(min_row=2, values_only=True):
    if row[1]:
        app = row[1]
    if row[2]:
        module = row[2]
    if app != TARGET or not row[5]:
        continue
    features[KEYS[module]] = [
        re.sub(r"^\d+\.\s*", "", line).strip()
        for line in str(row[5]).split("\n")
        if line.strip()
    ]

total = sum(len(v) for v in features.values())
expected_counts = {
    "landProfiling": 8,
    "inputs": 7,
    "cropMonitoring": 7,
    "advisory": 8,
    "valueChain": 7,
    "livestock": 7,
}
actual_counts = {k: len(features.get(k, [])) for k in expected_counts}
assert actual_counts == expected_counts, f"expected per-module counts {expected_counts}, got {actual_counts}"
assert total == 44, f"expected 44 features total, got {total}"

# Emit in a stable order so the generated file does not churn.
order = ["landProfiling", "inputs", "cropMonitoring", "advisory", "valueChain", "livestock"]
body = ",\n".join(
    f"  {k}: " + json.dumps(features[k], indent=2, ensure_ascii=False).replace("\n", "\n  ")
    for k in order
)

with open(OUT, "w") as f:
    f.write(
        "// GENERATED by scripts/extract-features.py - do not edit by hand.\n"
        f"// Source: {SRC}\n"
        f"// {len(features)} modules, {total} features.\n\n"
        "export const features = {\n" + body + ",\n}\n"
    )

print(f"wrote {OUT}: {len(features)} modules, {total} features")
