"""Build the portal's WebP image set from the photographer's originals.

Run:  python3 scripts/prepare-images.py

Sources are 4-6k px and 2-6 MB each and must never be served directly. Each
slug is written at up to three widths plus a tiny blurred LQIP, and the
manifest records only the widths actually produced, so a source that cannot
fill 1920 does not advertise a file that was never written. LQIPs are not
written to disk: at 24px wide they are only 80-120 bytes each, and an HTTP
request costs far more than that payload, so all ten are base64-inlined
straight into the generated manifest instead.
"""
import base64
import io
import os

from PIL import Image, ImageFilter

SRC_DIR = "/home/treasure/Pictures/Screenshots"
OUT_DIR = "public/images"
MANIFEST = "src/config/image-manifest.js"
WIDTHS = [640, 1280, 1920]

# The hero cross-fade preloads both hero-1-1920 and hero-2-1920 before
# anything else paints, so the 1920 tier sits on the critical path for every
# visitor, including those on constrained connections. 76 was not low enough
# to bring hero-1-1920 and hero-2-1920 under a 400 KB budget, so the 1920
# tier alone drops to 70; 640 and 1280 stay at 76 since smaller renders have
# less headroom to lose before compression artifacts show. A future
# maintainer raising either value back toward 82 should weigh that cost first.
QUALITY = 76
QUALITY_1920 = 70

# slug -> (source filename, crop box as fractions of (left, top, right, bottom))
#
# inputs-card is cropped down from the top: its flat grey sky is the one cool
# note in a warm palette, and losing most of it also strengthens the subject.
SOURCES = {
    # Absolute, so it overrides SRC_DIR: the field-with-tablet photograph the
    # login and home page share lives with the GeoHub site's imagery.
    "hero-1":              ("/home/treasure/Documents/projects2/Geohub/public/images/agr1.jpg", (0, 0, 1, 1)),
    "hero-2":              ("hero2.jpg",                (0, 0, 1, 1)),
    "land-profiling-card": ("lan profiling2.jpg",       (0, 0.18, 1, 1)),
    "inputs-card":         ("agriculture inputs2.jpg",  (0, 0.22, 1, 1)),
    "inputs-detail":       ("agriculture inputs1.jpg",  (0, 0, 1, 1)),
    "crop-monitoring-card":("crop monitoring.jpg",      (0, 0, 1, 1)),
    "advisory-card":       ("farmer advisory.jpg",      (0, 0, 1, 1)),
    "value-chain-card":    ("land profiling.jpg",       (0, 0, 1, 1)),
    "livestock-card":      ("livestock1.jpg",           (0, 0, 1, 1)),
    "livestock-detail":    ("livestock2.jpg",           (0, 0, 1, 1)),
}

os.makedirs(OUT_DIR, exist_ok=True)
manifest = {}
lqip = {}
inlined_bytes = 0

for slug, (filename, box) in SOURCES.items():
    path = os.path.join(SRC_DIR, filename)
    if not os.path.exists(path):
        raise SystemExit(f"missing source image: {path}")

    im = Image.open(path).convert("RGB")
    w, h = im.size
    im = im.crop((int(box[0] * w), int(box[1] * h), int(box[2] * w), int(box[3] * h)))

    written = []
    for width in WIDTHS:
        if im.width < width:
            continue
        scaled = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
        quality = QUALITY_1920 if width == 1920 else QUALITY
        scaled.save(os.path.join(OUT_DIR, f"{slug}-{width}.webp"), "WEBP", quality=quality, method=6)
        written.append(width)

    # Always emit the largest available width, even for a source narrower than
    # 640, so every slug has at least one real file behind it.
    if not written:
        im.save(os.path.join(OUT_DIR, f"{slug}-{im.width}.webp"), "WEBP", quality=QUALITY, method=6)
        written.append(im.width)

    lqip_im = im.resize((24, max(1, round(im.height * 24 / im.width))), Image.LANCZOS)
    lqip_im = lqip_im.filter(ImageFilter.GaussianBlur(1.2))
    buf = io.BytesIO()
    lqip_im.save(buf, "WEBP", quality=40)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    data_uri = f"data:image/webp;base64,{encoded}"
    lqip[slug] = data_uri
    inlined_bytes += len(data_uri)

    manifest[slug] = written
    print(f"{slug:22} {written}")

with open(MANIFEST, "w") as f:
    f.write("// GENERATED by scripts/prepare-images.py - do not edit by hand.\n\n")
    f.write("export const manifest = {\n")
    for slug, widths in manifest.items():
        f.write(f"  '{slug}': [{', '.join(str(x) for x in widths)}],\n")
    f.write("}\n\n")
    f.write("export const lqip = {\n")
    for slug, data_uri in lqip.items():
        f.write(f"  '{slug}': '{data_uri}',\n")
    f.write("}\n")

print(f"wrote {MANIFEST}: {len(manifest)} slugs")
print(f"inlined LQIP total: {inlined_bytes} bytes ({inlined_bytes / 1024:.1f} KB) across {len(lqip)} slugs")
